### ISSUE TITLE
MAJOR: Refactor/Commenting/Building Docs.

### ISSUE THREAD

**Issue by howie1329** [howie1329/WorkoutPal#17]
## Major

#Description 

- [ ] Refactor Code #18 
- [ ] Add Comments  #19 
- [ ] Start Building Documentation #20 
- [ ] Building Out Extensions and Organizing Code #30 
- [ ] Using Swift Lint #43
