### ISSUE TITLE
Feature: Feed Messages

### ISSUE THREAD

**Issue by howie1329** [howie1329/WorkoutPal#21]
## Description 
- [x] Allow creator of messages to be able to edit existing message #22 
- [x] Allow creator to delete existing message #23 
- [x] Add profile pic of creator to message #24 
- [x] Add like counter to message #25 
- [x] Add ability to have pictures in message #26
