### ISSUE TITLE
Feature: Sign Up Page With Profile Picture

### ISSUE THREAD

**Issue by howie1329** [howie1329/WorkoutPal#3]
# Sign up Page Profile Picture
ADD ABILITY TO UPLOAD PROFILE PICTURE TO USER DURING SIGN UP

## Description
This feature would allow users to upload a picture from their phone into the app.

## List of Task

- [x] Task 1: Update signup page for the ability to upload profile picture #4 
- [x] Task 2: Update Firebase database to find profile picture in firebase storage #5 
- [x] Task 3: Display profile picture in proper spots #2
